version: "3"

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    command: "dockerize -wait tcp://mongo:27017 yarn start"

  mongo:
    image: mongo:3.6
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data:
  node_modules:
